apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jdk-10
  template:
    metadata:
      labels:
        app: jdk-10
    spec:
      containers:
        - name: jdk-10
          image: openjdk:10-jdk-slim