apiVersion: v1
kind: Pod
metadata:
  name: sample-env
  labels:
    app: sample-app
spec:
  containers:
    - name: nginx-container
      image: tobi312/rpi-nginx:1.10
      env:
        - name: MAX_CONNECTION
          value: "100"
        - name: TZ
          value: Asia/Tokyo